import uuid

from datetime import datetime

from sqlalchemy import (
    Column,
    Float,
    Integer,
    String,
    Boolean,
    DateTime,
    ForeignKey,
    Text
)

from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from .base import Base


class Recommendation(Base):

    __tablename__ = "recommendations"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4
    )

    # ------------------------------------------------------------------------
    # User receiving the recommendation
    # ------------------------------------------------------------------------

    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "users.id",
            ondelete="CASCADE"
        ),
        nullable=True,
        index=True
    )

    # ------------------------------------------------------------------------
    # Recommended location
    # ------------------------------------------------------------------------

    location_id = Column(
        UUID(as_uuid=True),
        ForeignKey(
            "locations.id",
            ondelete="CASCADE"
        ),
        nullable=False,
        index=True
    )

    # ------------------------------------------------------------------------
    # Recommendation Intelligence
    # ------------------------------------------------------------------------

    recommendation_score = Column(
        Float,
        nullable=False
    )

    predicted_wait_minutes = Column(
        Integer,
        nullable=True
    )

    predicted_crowd_level = Column(
        Float,
        nullable=True
    )

    distance_km = Column(
        Float,
        nullable=True
    )

    estimated_travel_minutes = Column(
        Integer,
        nullable=True
    )

    # ------------------------------------------------------------------------
    # Explanation generated by WaitWise
    # ------------------------------------------------------------------------

    reason = Column(
        Text,
        nullable=True
    )

    recommendation_type = Column(
        String(100),
        default="smart_alternative",
        nullable=False
    )

    # ------------------------------------------------------------------------
    # User Feedback
    # ------------------------------------------------------------------------

    was_viewed = Column(
        Boolean,
        default=False,
        nullable=False
    )

    was_accepted = Column(
        Boolean,
        nullable=True
    )

    user_rating = Column(
        Float,
        nullable=True
    )

    feedback = Column(
        Text,
        nullable=True
    )

    # ------------------------------------------------------------------------
    # Timestamps
    # ------------------------------------------------------------------------

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True
    )

    expires_at = Column(
        DateTime,
        nullable=True
    )

    # ------------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------------

    user = relationship(
        "User"
    )

    location = relationship(
        "Location"
    )

    # ------------------------------------------------------------------------
    # Convert to API-friendly dictionary
    # ------------------------------------------------------------------------

    def to_dict(self):

        return {

            "id": str(self.id),

            "user_id": (
                str(self.user_id)
                if self.user_id else None
            ),

            "location_id": str(self.location_id),

            "recommendation_score":
            round(self.recommendation_score, 3),

            "predicted_wait_minutes":
            self.predicted_wait_minutes,

            "predicted_crowd_level":
            self.predicted_crowd_level,

            "distance_km":
            self.distance_km,

            "estimated_travel_minutes":
            self.estimated_travel_minutes,

            "reason":
            self.reason,

            "recommendation_type":
            self.recommendation_type,

            "was_viewed":
            self.was_viewed,

            "was_accepted":
            self.was_accepted,

            "user_rating":
            self.user_rating,

            "feedback":
            self.feedback,

            "created_at":
            (
                self.created_at.isoformat()
                if self.created_at else None
            ),

            "expires_at":
            (
                self.expires_at.isoformat()
                if self.expires_at else None
            )

        }

    # ------------------------------------------------------------------------
    # Check whether recommendation is still valid
    # ------------------------------------------------------------------------

    def is_expired(self):

        if not self.expires_at:
            return False

        return datetime.utcnow() > self.expires_at

    # ------------------------------------------------------------------------
    # Register user feedback
    # ------------------------------------------------------------------------

    def accept(self):

        self.was_viewed = True
        self.was_accepted = True

    def reject(self):

        self.was_viewed = True
        self.was_accepted = False

    # ------------------------------------------------------------------------
    # String representation
    # ------------------------------------------------------------------------

    def __repr__(self):

        return (

            f"<Recommendation "

            f"id={self.id} "

            f"location_id={self.location_id} "

            f"score={self.recommendation_score}>"

        )
